---

- name: install snapraid
  include_tasks: install-debian.yml
  when: ansible_os_family == 'Debian' and snapraid_install

- name: configure snapraid
  include_tasks: configure.yml

- name: install and configure snapraid-runner
  include_tasks: parity-checks.yml
  when: snapraid_runner

- name: schedule snapraid
  include_tasks: cron.yml
  when: not snapraid_runner
